import { Zone } from "@/types";

export const zones: Zone[] = [
  {
    id: "zone-1",
    slug: "entry",
    title: { en: "Entry Zone", es: "Zona de Entrada" },
    shortDescription: {
      en: "Welcome area and BookQuest Entry.",
      es: "Área de bienvenida y entrada a BookQuest.",
    },
    longDescription: {
      en: "The beginning of your PLAYce adventure! Get ready and oriented.",
      es: "¡El comienzo de tu aventura en PLAYce! Prepárate y oriéntate.",
    },
    colorToken: "playceBlue",
    icon: "DoorOpen", // Lucide icon name
    heroIllustration: "/images/playce/bookquest-entry.jpg",
    galleryImages: [
      "/images/playce/bookquest-entry.jpg",
      "/images/playce/bookquest-wall.jpg",
      "/images/playce/entry-overview.jpg",
      "/images/playce/signage.jpg",
    ],
    learningGoals: ["wayfinding", "literacy prep"],
    ageRanges: ["0-6"],
    featuredStations: ["bookquest"],
  },
  {
    id: "zone-2",
    slug: "baby-area",
    title: { en: "Baby Area", es: "Área para Bebés" },
    shortDescription: {
      en: "Sensory exploration and soft environment for pre-walkers.",
      es: "Exploración sensorial y entorno suave para bebés que aún no caminan.",
    },
    longDescription: {
      en: "A calm, sensory-focused environment with mirrors and tactile stimuli.",
      es: "Un ambiente tranquilo y centrado en los sentidos con espejos y estímulos táctiles.",
    },
    colorToken: "playceTeal",
    icon: "Baby",
    heroIllustration: "/images/playce/baby-area-tree.jpg",
    galleryImages: [
      "/images/playce/baby-area-tree.jpg",
      "/images/playce/baby-area-sensory.jpg",
      "/images/playce/design-approach-nature.jpg",
    ],
    learningGoals: ["sensory", "motor skills"],
    ageRanges: ["0-2"],
    featuredStations: ["baby-mirrors"],
  },
  {
    id: "zone-3",
    slug: "lagoon",
    title: { en: "Lagoon", es: "Laguna" },
    shortDescription: {
      en: "Nature-connected imaginative play with the Paddleboat and Pavilion.",
      es: "Juego imaginativo conectado con la naturaleza con el Bote de remos y el Pabellón.",
    },
    longDescription: {
      en: "An expressive, musical, nature-connected zone.",
      es: "Una zona expresiva, musical y conectada con la naturaleza.",
    },
    colorToken: "playceLeaf",
    icon: "Waves",
    heroIllustration: "/images/playce/lagoon-overview.jpg",
    galleryImages: [
      "/images/playce/lagoon-overview.jpg",
      "/images/playce/lagoon-paddleboat.jpg",
      "/images/playce/shimmer-tree.jpg",
      "/images/playce/shimmer-tree-detail.jpg",
      "/images/playce/pavilion.jpg",
      "/images/playce/lagoon-music.jpg",
    ],
    learningGoals: ["imagination", "vocabulary", "cause and effect"],
    ageRanges: ["2-6"],
    featuredStations: ["paddleboat", "pavilion", "shimmer-tree"],
  },
  {
    id: "zone-4",
    slug: "city",
    title: { en: "City", es: "Ciudad" },
    shortDescription: {
      en: "Bustling social play featuring Farmers Market and First Responders.",
      es: "Juego social bullicioso con el Mercado de Agricultores y Primeros Respondedores.",
    },
    longDescription: {
      en: "A rich, social section that feels bustling, bringing local Beloit landmarks to life.",
      es: "Una sección rica y social que se siente bulliciosa, dando vida a lugares emblemáticos de Beloit.",
    },
    colorToken: "playceSun",
    icon: "Building2",
    heroIllustration: "/images/playce/city-facades.jpg",
    galleryImages: [
      "/images/playce/city-facades.jpg",
      "/images/playce/city-overview.jpg",
      "/images/playce/farmers-market.jpg",
      "/images/playce/fire-station.jpg",
      "/images/playce/school-bus.jpg",
      "/images/playce/play-table.jpg",
      "/images/playce/play-table-detail.jpg",
    ],
    learningGoals: ["numeracy", "social skills", "roleplay"],
    ageRanges: ["2-6"],
    featuredStations: ["farmers-market", "school-bus", "community-kitchen"],
  },
  {
    id: "zone-5",
    slug: "home",
    title: { en: "Home", es: "Casa" },
    shortDescription: {
      en: "Daily routines, comfort, and household role play.",
      es: "Rutinas diarias, comodidad y juegos de rol en el hogar.",
    },
    longDescription: {
      en: "Focuses on daily routines like laundry, grooming, and bedtime.",
      es: "Se centra en rutinas diarias como lavar la ropa, el aseo personal y la hora de acostarse.",
    },
    colorToken: "playceCoral",
    icon: "Home",
    heroIllustration: "/images/playce/home-zone.jpg",
    galleryImages: [
      "/images/playce/home-zone.jpg",
      "/images/playce/home-overview.jpg",
      "/images/playce/laundry-station.jpg",
      "/images/playce/laundry-detail.jpg",
      "/images/playce/kitchen-station.jpg",
      "/images/playce/bathroom-station.jpg",
      "/images/playce/bathroom-detail.jpg",
      "/images/playce/bathroom-rendering.jpg",
    ],
    learningGoals: ["daily skills", "routine", "responsibility"],
    ageRanges: ["1-6"],
    featuredStations: ["laundry", "bathroom", "nursery"],
  },
];
